import re

# Initialize tables for each subGroup
split_data = {
    "1.Very High 10000+": [],
    "2.High 1000+": [],
    "3.Medium 100+": [],
    "4.Low 10+": [],
    "5.Very low 1+": []
}

# Read and parse the Data.lua file
with open('Data.lua', 'r') as file:
    content = file.read()
    # Find all item entries using regex
    items = re.findall(r'\[(\d+)\] = { -- (.+?)\n\s+name = "(.+?)",\n\s+subGroup = "(.+?)",\n\s+marketValue = (.+?),\n\s+saleRate = (.+?)\n\s+}', content)
    
    # Sort items into appropriate subGroup tables
    for item in items:
        itemId, comment, name, subGroup, marketValue, saleRate = item
        if subGroup in split_data:
            split_data[subGroup].append({
                'id': itemId,
                'comment': comment,
                'name': name,
                'subGroup': subGroup,
                'marketValue': marketValue,
                'saleRate': saleRate
            })

# Write each subGroup to its own file
for subGroup, items in split_data.items():
    # Create sanitized filename
    filename = f"Data_{subGroup.replace(' ', '_').replace('+', 'plus')}.lua"
    
    with open(filename, 'w') as file:
        file.write("-- Auto-generated by data splitter\n")
        file.write(f"FLIPR_ItemDatabase_{subGroup.replace('.', '').replace(' ', '').replace('+', 'plus')} = {{\n")
        
        # Sort items by ID for consistent output
        items.sort(key=lambda x: int(x['id']))
        
        for item in items:
            file.write(f"    [{item['id']}] = {{ -- {item['comment']}\n")
            file.write(f"        name = \"{item['name']}\",\n")
            file.write(f"        subGroup = \"{item['subGroup']}\",\n")
            file.write(f"        marketValue = {item['marketValue']},\n")
            file.write(f"        saleRate = {item['saleRate']}\n")
            file.write("    },\n")
            
        file.write("}\n")

print("Data split complete!") 