-- Auto-generated by data splitter
FLIPR_ItemDatabase_1VeryHigh10000plus = {
    [118] = { -- Minor Healing Potion
        name = "Minor Healing Potion",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0193,
        saleRate = 0.382
    },
    [765] = { -- Silverleaf
        name = "Silverleaf",
        subGroup = "1.Very High 10000+",
        marketValue = 4.3785,
        saleRate = 0.627
    },
    [785] = { -- Mageroyal
        name = "Mageroyal",
        subGroup = "1.Very High 10000+",
        marketValue = 2.7998,
        saleRate = 0.642
    },
    [1288] = { -- Large Venom Sac
        name = "Large Venom Sac",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0531,
        saleRate = 0.3
    },
    [2318] = { -- Light Leather
        name = "Light Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 1.4766,
        saleRate = 0.169
    },
    [2319] = { -- Medium Leather
        name = "Medium Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 3.8581,
        saleRate = 0.368
    },
    [2320] = { -- Coarse Thread
        name = "Coarse Thread",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0317,
        saleRate = 0.337
    },
    [2321] = { -- Fine Thread
        name = "Fine Thread",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0171,
        saleRate = 0.191
    },
    [2324] = { -- Bleach
        name = "Bleach",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0165,
        saleRate = 0.188
    },
    [2447] = { -- Peacebloom
        name = "Peacebloom",
        subGroup = "1.Very High 10000+",
        marketValue = 4.6771,
        saleRate = 0.441
    },
    [2449] = { -- Earthroot
        name = "Earthroot",
        subGroup = "1.Very High 10000+",
        marketValue = 4.1047,
        saleRate = 0.423
    },
    [2452] = { -- Swiftthistle
        name = "Swiftthistle",
        subGroup = "1.Very High 10000+",
        marketValue = 3.131,
        saleRate = 0.474
    },
    [2453] = { -- Bruiseweed
        name = "Bruiseweed",
        subGroup = "1.Very High 10000+",
        marketValue = 2.8171,
        saleRate = 0.696
    },
    [2589] = { -- Linen Cloth
        name = "Linen Cloth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0744,
        saleRate = 0.335
    },
    [2592] = { -- Wool Cloth
        name = "Wool Cloth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0722,
        saleRate = 0.523
    },
    [2604] = { -- Red Dye
        name = "Red Dye",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1047,
        saleRate = 0.145
    },
    [2605] = { -- Green Dye
        name = "Green Dye",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0924,
        saleRate = 0.163
    },
    [2678] = { -- Mild Spices
        name = "Mild Spices",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0137,
        saleRate = 0.115
    },
    [2771] = { -- Tin Ore
        name = "Tin Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 1.8122,
        saleRate = 0.558
    },
    [2776] = { -- Gold Ore
        name = "Gold Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 19.4761,
        saleRate = 0.498
    },
    [2835] = { -- Rough Stone
        name = "Rough Stone",
        subGroup = "1.Very High 10000+",
        marketValue = 0.046,
        saleRate = 0.464
    },
    [2836] = { -- Coarse Stone
        name = "Coarse Stone",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0965,
        saleRate = 0.421
    },
    [2838] = { -- Heavy Stone
        name = "Heavy Stone",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0591,
        saleRate = 0.4
    },
    [2880] = { -- Weak Flux
        name = "Weak Flux",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0703,
        saleRate = 0.202
    },
    [2996] = { -- Bolt of Linen Cloth
        name = "Bolt of Linen Cloth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1215,
        saleRate = 0.337
    },
    [3356] = { -- Kingsblood
        name = "Kingsblood",
        subGroup = "1.Very High 10000+",
        marketValue = 9.1798,
        saleRate = 0.786
    },
    [3371] = { -- Crystal Vial
        name = "Crystal Vial",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0118,
        saleRate = 0.24
    },
    [3576] = { -- Tin Bar
        name = "Tin Bar",
        subGroup = "1.Very High 10000+",
        marketValue = 1.9869,
        saleRate = 0.637
    },
    [3857] = { -- Coal
        name = "Coal",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0878,
        saleRate = 0.223
    },
    [3858] = { -- Mithril Ore
        name = "Mithril Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 11.0149,
        saleRate = 0.713
    },
    [3859] = { -- Steel Bar
        name = "Steel Bar",
        subGroup = "1.Very High 10000+",
        marketValue = 7.7328,
        saleRate = 0.282
    },
    [3860] = { -- Mithril Bar
        name = "Mithril Bar",
        subGroup = "1.Very High 10000+",
        marketValue = 13.5928,
        saleRate = 0.529
    },
    [4234] = { -- Heavy Leather
        name = "Heavy Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 7.8395,
        saleRate = 0.033
    },
    [4289] = { -- Salt
        name = "Salt",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0722,
        saleRate = 0.146
    },
    [4291] = { -- Silken Thread
        name = "Silken Thread",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0919,
        saleRate = 0.18
    },
    [4304] = { -- Thick Leather
        name = "Thick Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 6.1319,
        saleRate = 0.197
    },
    [4306] = { -- Silk Cloth
        name = "Silk Cloth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0972,
        saleRate = 0.461
    },
    [4338] = { -- Mageweave Cloth
        name = "Mageweave Cloth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0662,
        saleRate = 0.417
    },
    [4339] = { -- Bolt of Mageweave
        name = "Bolt of Mageweave",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3972,
        saleRate = 0.305
    },
    [4359] = { -- Handful of Copper Bolts
        name = "Handful of Copper Bolts",
        subGroup = "1.Very High 10000+",
        marketValue = 9.6063,
        saleRate = 0.297
    },
    [4470] = { -- Simple Wood
        name = "Simple Wood",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0204,
        saleRate = 0.221
    },
    [6260] = { -- Blue Dye
        name = "Blue Dye",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1408,
        saleRate = 0.224
    },
    [6289] = { -- Raw Longjaw Mud Snapper
        name = "Raw Longjaw Mud Snapper",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1444,
        saleRate = 0.491
    },
    [6291] = { -- Raw Brilliant Smallfish
        name = "Raw Brilliant Smallfish",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1761,
        saleRate = 0.467
    },
    [6308] = { -- Raw Bristle Whisker Catfish
        name = "Raw Bristle Whisker Catfish",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3106,
        saleRate = 0.545
    },
    [6361] = { -- Raw Rainbow Fin Albacore
        name = "Raw Rainbow Fin Albacore",
        subGroup = "1.Very High 10000+",
        marketValue = 1.0587,
        saleRate = 0.075
    },
    [6657] = { -- Savory Deviate Delight
        name = "Savory Deviate Delight",
        subGroup = "1.Very High 10000+",
        marketValue = 24.2929,
        saleRate = 0.331
    },
    [6662] = { -- Elixir of Giant Growth
        name = "Elixir of Giant Growth",
        subGroup = "1.Very High 10000+",
        marketValue = 35.6117,
        saleRate = 0.444
    },
    [7068] = { -- Elemental Fire
        name = "Elemental Fire",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0509,
        saleRate = 0.36
    },
    [7075] = { -- Core of Earth
        name = "Core of Earth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.15,
        saleRate = 0.088
    },
    [7078] = { -- Essence of Fire
        name = "Essence of Fire",
        subGroup = "1.Very High 10000+",
        marketValue = 0.5766,
        saleRate = 0.557
    },
    [7912] = { -- Solid Stone
        name = "Solid Stone",
        subGroup = "1.Very High 10000+",
        marketValue = 6.1264,
        saleRate = 0.776
    },
    [7974] = { -- Zesty Clam Meat
        name = "Zesty Clam Meat",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1672,
        saleRate = 0.2
    },
    [8154] = { -- Scorpid Scale
        name = "Scorpid Scale",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1908,
        saleRate = 0.136
    },
    [8170] = { -- Rugged Leather
        name = "Rugged Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 2.656,
        saleRate = 0.523
    },
    [10286] = { -- Heart of the Wild
        name = "Heart of the Wild",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1065,
        saleRate = 0.113
    },
    [10560] = { -- Unstable Trigger
        name = "Unstable Trigger",
        subGroup = "1.Very High 10000+",
        marketValue = 40.8582,
        saleRate = 0.396
    },
    [10620] = { -- Thorium Ore
        name = "Thorium Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 9.5337,
        saleRate = 0.614
    },
    [10938] = { -- Lesser Magic Essence
        name = "Lesser Magic Essence",
        subGroup = "1.Very High 10000+",
        marketValue = 1.2889,
        saleRate = 0.414
    },
    [10939] = { -- Greater Magic Essence
        name = "Greater Magic Essence",
        subGroup = "1.Very High 10000+",
        marketValue = 2.3737,
        saleRate = 0.331
    },
    [10940] = { -- Strange Dust
        name = "Strange Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 0.9158,
        saleRate = 0.145
    },
    [12037] = { -- Mystery Meat
        name = "Mystery Meat",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0362,
        saleRate = 0.425
    },
    [12203] = { -- Red Wolf Meat
        name = "Red Wolf Meat",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0357,
        saleRate = 0.734
    },
    [12205] = { -- White Spider Meat
        name = "White Spider Meat",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1992,
        saleRate = 0.708
    },
    [12208] = { -- Tender Wolf Meat
        name = "Tender Wolf Meat",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1453,
        saleRate = 0.162
    },
    [12359] = { -- Thorium Bar
        name = "Thorium Bar",
        subGroup = "1.Very High 10000+",
        marketValue = 11.37,
        saleRate = 0.378
    },
    [12365] = { -- Dense Stone
        name = "Dense Stone",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0321,
        saleRate = 0.092
    },
    [14047] = { -- Runecloth
        name = "Runecloth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.7718,
        saleRate = 0.625
    },
    [14048] = { -- Bolt of Runecloth
        name = "Bolt of Runecloth",
        subGroup = "1.Very High 10000+",
        marketValue = 1.2698,
        saleRate = 0.152
    },
    [14343] = { -- Small Brilliant Shard
        name = "Small Brilliant Shard",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3603,
        saleRate = 0.251
    },
    [14344] = { -- Large Brilliant Shard
        name = "Large Brilliant Shard",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2724,
        saleRate = 0.68
    },
    [15994] = { -- Thorium Widget
        name = "Thorium Widget",
        subGroup = "1.Very High 10000+",
        marketValue = 44.7562,
        saleRate = 0.241
    },
    [16203] = { -- Greater Eternal Essence
        name = "Greater Eternal Essence",
        subGroup = "1.Very High 10000+",
        marketValue = 4.3528,
        saleRate = 0.152
    },
    [17202] = { -- Snowball
        name = "Snowball",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1634,
        saleRate = 0.078
    },
    [18945] = { -- Dark Iron Residue
        name = "Dark Iron Residue",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0817,
        saleRate = 0.319
    },
    [19183] = { -- Hourglass Sand
        name = "Hourglass Sand",
        subGroup = "1.Very High 10000+",
        marketValue = 0.01,
        saleRate = 0.062
    },
    [20404] = { -- Encrypted Twilight Text
        name = "Encrypted Twilight Text",
        subGroup = "1.Very High 10000+",
        marketValue = 3.3257,
        saleRate = 0.083
    },
    [21877] = { -- Netherweave Cloth
        name = "Netherweave Cloth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0851,
        saleRate = 0.408
    },
    [22445] = { -- Arcane Dust
        name = "Arcane Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 0.9023,
        saleRate = 0.244
    },
    [23425] = { -- Adamantite Ore
        name = "Adamantite Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 4.9975,
        saleRate = 0.578
    },
    [23446] = { -- Adamantite Bar
        name = "Adamantite Bar",
        subGroup = "1.Very High 10000+",
        marketValue = 12.1964,
        saleRate = 0.421
    },
    [24477] = { -- Jaggal Clam Meat
        name = "Jaggal Clam Meat",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0756,
        saleRate = 0.447
    },
    [25708] = { -- Thick Clefthoof Leather
        name = "Thick Clefthoof Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 70.6727,
        saleRate = 0.011
    },
    [29739] = { -- Arcane Tome
        name = "Arcane Tome",
        subGroup = "1.Very High 10000+",
        marketValue = 1.567,
        saleRate = 0.145
    },
    [30809] = { -- Mark of Sargeras
        name = "Mark of Sargeras",
        subGroup = "1.Very High 10000+",
        marketValue = 6.3579,
        saleRate = 0.108
    },
    [30810] = { -- Sunfury Signet
        name = "Sunfury Signet",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1779,
        saleRate = 0.358
    },
    [30817] = { -- Simple Flour
        name = "Simple Flour",
        subGroup = "1.Very High 10000+",
        marketValue = 0.021,
        saleRate = 0.205
    },
    [32897] = { -- Mark of the Illidari
        name = "Mark of the Illidari",
        subGroup = "1.Very High 10000+",
        marketValue = 0.6515,
        saleRate = 0.535
    },
    [33470] = { -- Frostweave Cloth
        name = "Frostweave Cloth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2316,
        saleRate = 0.614
    },
    [33568] = { -- Borean Leather
        name = "Borean Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 1.9821,
        saleRate = 0.269
    },
    [34054] = { -- Infinite Dust
        name = "Infinite Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 0.5094,
        saleRate = 0.023
    },
    [36906] = { -- Icethorn
        name = "Icethorn",
        subGroup = "1.Very High 10000+",
        marketValue = 3.7432,
        saleRate = 0.494
    },
    [36909] = { -- Cobalt Ore
        name = "Cobalt Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 26.1082,
        saleRate = 0.275
    },
    [36912] = { -- Saronite Ore
        name = "Saronite Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 14.8437,
        saleRate = 0.48
    },
    [36916] = { -- Cobalt Bar
        name = "Cobalt Bar",
        subGroup = "1.Very High 10000+",
        marketValue = 29.4306,
        saleRate = 0.213
    },
    [37701] = { -- Crystallized Earth
        name = "Crystallized Earth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3964,
        saleRate = 0.523
    },
    [38682] = { -- Enchanting Vellum
        name = "Enchanting Vellum",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1657,
        saleRate = 0.572
    },
    [39354] = { -- Light Parchment
        name = "Light Parchment",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0151,
        saleRate = 0.175
    },
    [41810] = { -- Fangtooth Herring
        name = "Fangtooth Herring",
        subGroup = "1.Very High 10000+",
        marketValue = 0.6804,
        saleRate = 0.046
    },
    [42780] = { -- Relic of Ulduar
        name = "Relic of Ulduar",
        subGroup = "1.Very High 10000+",
        marketValue = 0.6612,
        saleRate = 0.285
    },
    [43007] = { -- Northern Spices
        name = "Northern Spices",
        subGroup = "1.Very High 10000+",
        marketValue = 1.4075,
        saleRate = 0.13
    },
    [43011] = { -- Worg Haunch
        name = "Worg Haunch",
        subGroup = "1.Very High 10000+",
        marketValue = 0.6322,
        saleRate = 0.595
    },
    [45087] = { -- Runed Orb
        name = "Runed Orb",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2351,
        saleRate = 0.342
    },
    [52186] = { -- Elementium Bar
        name = "Elementium Bar",
        subGroup = "1.Very High 10000+",
        marketValue = 26.0146,
        saleRate = 0.159
    },
    [52325] = { -- Volatile Fire
        name = "Volatile Fire",
        subGroup = "1.Very High 10000+",
        marketValue = 9.0481,
        saleRate = 0.047
    },
    [52327] = { -- Volatile Earth
        name = "Volatile Earth",
        subGroup = "1.Very High 10000+",
        marketValue = 7.0698,
        saleRate = 0.097
    },
    [52329] = { -- Volatile Life
        name = "Volatile Life",
        subGroup = "1.Very High 10000+",
        marketValue = 13.6364,
        saleRate = 0.152
    },
    [52555] = { -- Hypnotic Dust
        name = "Hypnotic Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 6.6601,
        saleRate = 0.696
    },
    [52988] = { -- Whiptail
        name = "Whiptail",
        subGroup = "1.Very High 10000+",
        marketValue = 8.5483,
        saleRate = 0.227
    },
    [53010] = { -- Embersilk Cloth
        name = "Embersilk Cloth",
        subGroup = "1.Very High 10000+",
        marketValue = 1.5987,
        saleRate = 0.477
    },
    [72092] = { -- Ghost Iron Ore
        name = "Ghost Iron Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 4.9144,
        saleRate = 0.495
    },
    [72093] = { -- Kyparite
        name = "Kyparite",
        subGroup = "1.Very High 10000+",
        marketValue = 0.6918,
        saleRate = 0.63
    },
    [72096] = { -- Ghost Iron Bar
        name = "Ghost Iron Bar",
        subGroup = "1.Very High 10000+",
        marketValue = 11.0833,
        saleRate = 0.392
    },
    [72103] = { -- White Trillium Ore
        name = "White Trillium Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 16.482,
        saleRate = 0.122
    },
    [72120] = { -- Mist-Touched Leather
        name = "Mist-Touched Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1422,
        saleRate = 0.485
    },
    [72234] = { -- Green Tea Leaf
        name = "Green Tea Leaf",
        subGroup = "1.Very High 10000+",
        marketValue = 0.5908,
        saleRate = 0.46
    },
    [72238] = { -- Golden Lotus
        name = "Golden Lotus",
        subGroup = "1.Very High 10000+",
        marketValue = 7.4898,
        saleRate = 0.156
    },
    [72988] = { -- Windwool Cloth
        name = "Windwool Cloth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2227,
        saleRate = 0.6
    },
    [74249] = { -- Spirit Dust
        name = "Spirit Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0651,
        saleRate = 0.21
    },
    [76061] = { -- Spirit of Harmony
        name = "Spirit of Harmony",
        subGroup = "1.Very High 10000+",
        marketValue = 95.1699,
        saleRate = 0.121
    },
    [89112] = { -- Mote of Harmony
        name = "Mote of Harmony",
        subGroup = "1.Very High 10000+",
        marketValue = 9.1636,
        saleRate = 0.119
    },
    [90407] = { -- Sparkling Shard
        name = "Sparkling Shard",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1694,
        saleRate = 0.129
    },
    [94288] = { -- Giant Dinosaur Bone
        name = "Giant Dinosaur Bone",
        subGroup = "1.Very High 10000+",
        marketValue = 2.1529,
        saleRate = 0.128
    },
    [108996] = { -- Alchemical Catalyst
        name = "Alchemical Catalyst",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0982,
        saleRate = 0.647
    },
    [109076] = { -- Goblin Glider Kit
        name = "Goblin Glider Kit",
        subGroup = "1.Very High 10000+",
        marketValue = 3.209,
        saleRate = 0.547
    },
    [109118] = { -- Blackrock Ore
        name = "Blackrock Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3168,
        saleRate = 0.345
    },
    [109119] = { -- True Iron Ore
        name = "True Iron Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 1.1178,
        saleRate = 0.788
    },
    [109124] = { -- Frostweed
        name = "Frostweed",
        subGroup = "1.Very High 10000+",
        marketValue = 0.9718,
        saleRate = 0.494
    },
    [109125] = { -- Fireweed
        name = "Fireweed",
        subGroup = "1.Very High 10000+",
        marketValue = 0.9378,
        saleRate = 0.508
    },
    [109126] = { -- Gorgrond Flytrap
        name = "Gorgrond Flytrap",
        subGroup = "1.Very High 10000+",
        marketValue = 0.9599,
        saleRate = 0.571
    },
    [109127] = { -- Starflower
        name = "Starflower",
        subGroup = "1.Very High 10000+",
        marketValue = 0.9501,
        saleRate = 0.426
    },
    [109128] = { -- Nagrand Arrowbloom
        name = "Nagrand Arrowbloom",
        subGroup = "1.Very High 10000+",
        marketValue = 0.9374,
        saleRate = 0.556
    },
    [109129] = { -- Talador Orchid
        name = "Talador Orchid",
        subGroup = "1.Very High 10000+",
        marketValue = 0.9421,
        saleRate = 0.407
    },
    [109131] = { -- Raw Clefthoof Meat
        name = "Raw Clefthoof Meat",
        subGroup = "1.Very High 10000+",
        marketValue = 2.2794,
        saleRate = 0.789
    },
    [109138] = { -- Jawless Skulker Flesh
        name = "Jawless Skulker Flesh",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2416,
        saleRate = 0.284
    },
    [109139] = { -- Fat Sleeper Flesh
        name = "Fat Sleeper Flesh",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1357,
        saleRate = 0.543
    },
    [109140] = { -- Blind Lake Sturgeon Flesh
        name = "Blind Lake Sturgeon Flesh",
        subGroup = "1.Very High 10000+",
        marketValue = 0.4661,
        saleRate = 0.449
    },
    [109141] = { -- Fire Ammonite Tentacle
        name = "Fire Ammonite Tentacle",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1271,
        saleRate = 0.695
    },
    [109142] = { -- Sea Scorpion Segment
        name = "Sea Scorpion Segment",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2282,
        saleRate = 0.385
    },
    [109143] = { -- Abyssal Gulper Eel Flesh
        name = "Abyssal Gulper Eel Flesh",
        subGroup = "1.Very High 10000+",
        marketValue = 5.8538,
        saleRate = 0.584
    },
    [109144] = { -- Blackwater Whiptail Flesh
        name = "Blackwater Whiptail Flesh",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0618,
        saleRate = 0.316
    },
    [109693] = { -- Draenic Dust
        name = "Draenic Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 0.5609,
        saleRate = 0.241
    },
    [110609] = { -- Raw Beast Hide
        name = "Raw Beast Hide",
        subGroup = "1.Very High 10000+",
        marketValue = 0.928,
        saleRate = 0.351
    },
    [110610] = { -- Raw Beast Hide Scraps
        name = "Raw Beast Hide Scraps",
        subGroup = "1.Very High 10000+",
        marketValue = 0.186,
        saleRate = 0.267
    },
    [111557] = { -- Sumptuous Fur
        name = "Sumptuous Fur",
        subGroup = "1.Very High 10000+",
        marketValue = 1.1801,
        saleRate = 0.471
    },
    [111670] = { -- Enormous Blackwater Whiptail
        name = "Enormous Blackwater Whiptail",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3898,
        saleRate = 0.302
    },
    [113261] = { -- Sorcerous Fire
        name = "Sorcerous Fire",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2179,
        saleRate = 0.333
    },
    [113262] = { -- Sorcerous Water
        name = "Sorcerous Water",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1183,
        saleRate = 0.197
    },
    [113263] = { -- Sorcerous Earth
        name = "Sorcerous Earth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3707,
        saleRate = 0.641
    },
    [113264] = { -- Sorcerous Air
        name = "Sorcerous Air",
        subGroup = "1.Very High 10000+",
        marketValue = 0.118,
        saleRate = 0.464
    },
    [113355] = { -- Card of Omens
        name = "Card of Omens",
        subGroup = "1.Very High 10000+",
        marketValue = 4.1501,
        saleRate = 0.365
    },
    [116271] = { -- Draenic Water Breathing Elixir
        name = "Draenic Water Breathing Elixir",
        subGroup = "1.Very High 10000+",
        marketValue = 42.2255,
        saleRate = 0.402
    },
    [118391] = { -- Worm Supreme
        name = "Worm Supreme",
        subGroup = "1.Very High 10000+",
        marketValue = 0.5056,
        saleRate = 0.268
    },
    [118711] = { -- Draenic Water Walking Elixir
        name = "Draenic Water Walking Elixir",
        subGroup = "1.Very High 10000+",
        marketValue = 31.028,
        saleRate = 0.41
    },
    [123918] = { -- Leystone Ore
        name = "Leystone Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 16.3553,
        saleRate = 0.249
    },
    [123919] = { -- Felslate
        name = "Felslate",
        subGroup = "1.Very High 10000+",
        marketValue = 1.4598,
        saleRate = 0.102
    },
    [124101] = { -- Aethril
        name = "Aethril",
        subGroup = "1.Very High 10000+",
        marketValue = 9.7599,
        saleRate = 0.453
    },
    [124102] = { -- Dreamleaf
        name = "Dreamleaf",
        subGroup = "1.Very High 10000+",
        marketValue = 12.4932,
        saleRate = 0.56
    },
    [124104] = { -- Fjarnskaggl
        name = "Fjarnskaggl",
        subGroup = "1.Very High 10000+",
        marketValue = 10.0234,
        saleRate = 0.272
    },
    [124113] = { -- Stonehide Leather
        name = "Stonehide Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 0.6833,
        saleRate = 0.344
    },
    [124115] = { -- Stormscale
        name = "Stormscale",
        subGroup = "1.Very High 10000+",
        marketValue = 1.4548,
        saleRate = 0.249
    },
    [124117] = { -- Lean Shank
        name = "Lean Shank",
        subGroup = "1.Very High 10000+",
        marketValue = 1.4491,
        saleRate = 0.834
    },
    [124118] = { -- Fatty Bearsteak
        name = "Fatty Bearsteak",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0794,
        saleRate = 0.61
    },
    [124119] = { -- Big Gamy Ribs
        name = "Big Gamy Ribs",
        subGroup = "1.Very High 10000+",
        marketValue = 1.5068,
        saleRate = 0.178
    },
    [124120] = { -- Leyblood
        name = "Leyblood",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0158,
        saleRate = 0.768
    },
    [124121] = { -- Wildfowl Egg
        name = "Wildfowl Egg",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0371,
        saleRate = 0.627
    },
    [124437] = { -- Shal'dorei Silk
        name = "Shal'dorei Silk",
        subGroup = "1.Very High 10000+",
        marketValue = 0.4148,
        saleRate = 0.264
    },
    [124438] = { -- Unbroken Claw
        name = "Unbroken Claw",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0135,
        saleRate = 0.428
    },
    [124439] = { -- Unbroken Tooth
        name = "Unbroken Tooth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0152,
        saleRate = 0.488
    },
    [124440] = { -- Arkhana
        name = "Arkhana",
        subGroup = "1.Very High 10000+",
        marketValue = 1.09,
        saleRate = 0.404
    },
    [124441] = { -- Leylight Shard
        name = "Leylight Shard",
        subGroup = "1.Very High 10000+",
        marketValue = 1.2805,
        saleRate = 0.098
    },
    [124442] = { -- Chaos Crystal
        name = "Chaos Crystal",
        subGroup = "1.Very High 10000+",
        marketValue = 6.6164,
        saleRate = 0.167
    },
    [124669] = { -- Darkmoon Daggermaw
        name = "Darkmoon Daggermaw",
        subGroup = "1.Very High 10000+",
        marketValue = 16.0517,
        saleRate = 0.601
    },
    [127759] = { -- Felblight
        name = "Felblight",
        subGroup = "1.Very High 10000+",
        marketValue = 0.6926,
        saleRate = 0.466
    },
    [129032] = { -- Roseate Pigment
        name = "Roseate Pigment",
        subGroup = "1.Very High 10000+",
        marketValue = 13.538,
        saleRate = 0.341
    },
    [142335] = { -- Pristine Falcosaur Feather
        name = "Pristine Falcosaur Feather",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0237,
        saleRate = 0.325
    },
    [151564] = { -- Empyrium
        name = "Empyrium",
        subGroup = "1.Very High 10000+",
        marketValue = 5.4113,
        saleRate = 0.224
    },
    [151566] = { -- Fiendish Leather
        name = "Fiendish Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3205,
        saleRate = 0.381
    },
    [152505] = { -- Riverbud
        name = "Riverbud",
        subGroup = "1.Very High 10000+",
        marketValue = 2.0302,
        saleRate = 0.494
    },
    [152506] = { -- Star Moss
        name = "Star Moss",
        subGroup = "1.Very High 10000+",
        marketValue = 2.1156,
        saleRate = 0.461
    },
    [152507] = { -- Akunda's Bite
        name = "Akunda's Bite",
        subGroup = "1.Very High 10000+",
        marketValue = 3.0784,
        saleRate = 0.619
    },
    [152508] = { -- Winter's Kiss
        name = "Winter's Kiss",
        subGroup = "1.Very High 10000+",
        marketValue = 2.0828,
        saleRate = 0.424
    },
    [152509] = { -- Siren's Pollen
        name = "Siren's Pollen",
        subGroup = "1.Very High 10000+",
        marketValue = 2.6683,
        saleRate = 0.739
    },
    [152510] = { -- Anchor Weed
        name = "Anchor Weed",
        subGroup = "1.Very High 10000+",
        marketValue = 7.0997,
        saleRate = 0.048
    },
    [152512] = { -- Monelite Ore
        name = "Monelite Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 10.5568,
        saleRate = 0.263
    },
    [152513] = { -- Platinum Ore
        name = "Platinum Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 2.0466,
        saleRate = 0.302
    },
    [152541] = { -- Coarse Leather
        name = "Coarse Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 0.452,
        saleRate = 0.621
    },
    [152542] = { -- Hardened Tempest Hide
        name = "Hardened Tempest Hide",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0317,
        saleRate = 0.191
    },
    [152576] = { -- Tidespray Linen
        name = "Tidespray Linen",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1565,
        saleRate = 0.267
    },
    [152577] = { -- Deep Sea Satin
        name = "Deep Sea Satin",
        subGroup = "1.Very High 10000+",
        marketValue = 3.2982,
        saleRate = 0.327
    },
    [152579] = { -- Storm Silver Ore
        name = "Storm Silver Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 11.543,
        saleRate = 0.241
    },
    [152875] = { -- Gloom Dust
        name = "Gloom Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 1.7431,
        saleRate = 0.284
    },
    [152876] = { -- Umbra Shard
        name = "Umbra Shard",
        subGroup = "1.Very High 10000+",
        marketValue = 4.3084,
        saleRate = 0.185
    },
    [152877] = { -- Veiled Crystal
        name = "Veiled Crystal",
        subGroup = "1.Very High 10000+",
        marketValue = 8.6411,
        saleRate = 0.026
    },
    [153050] = { -- Shimmerscale
        name = "Shimmerscale",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1792,
        saleRate = 0.708
    },
    [153051] = { -- Mistscale
        name = "Mistscale",
        subGroup = "1.Very High 10000+",
        marketValue = 0.041,
        saleRate = 0.372
    },
    [153635] = { -- Ultramarine Pigment
        name = "Ultramarine Pigment",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0359,
        saleRate = 0.278
    },
    [153669] = { -- Viridescent Pigment
        name = "Viridescent Pigment",
        subGroup = "1.Very High 10000+",
        marketValue = 0.036,
        saleRate = 0.236
    },
    [154164] = { -- Blood-Stained Bone
        name = "Blood-Stained Bone",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2217,
        saleRate = 0.172
    },
    [154165] = { -- Calcified Bone
        name = "Calcified Bone",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0254,
        saleRate = 0.366
    },
    [154722] = { -- Tempest Hide
        name = "Tempest Hide",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0286,
        saleRate = 0.094
    },
    [154897] = { -- Stringy Loins
        name = "Stringy Loins",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0714,
        saleRate = 0.442
    },
    [154899] = { -- Thick Paleo Steak
        name = "Thick Paleo Steak",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0881,
        saleRate = 0.186
    },
    [156930] = { -- Rich Illusion Dust
        name = "Rich Illusion Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3929,
        saleRate = 0.376
    },
    [158186] = { -- Distilled Water
        name = "Distilled Water",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0467,
        saleRate = 0.25
    },
    [158378] = { -- Embroidered Deep Sea Satin
        name = "Embroidered Deep Sea Satin",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1009,
        saleRate = 0.222
    },
    [160059] = { -- Amber Tanning Oil
        name = "Amber Tanning Oil",
        subGroup = "1.Very High 10000+",
        marketValue = 0.038,
        saleRate = 0.297
    },
    [163569] = { -- Insulated Wiring
        name = "Insulated Wiring",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0121,
        saleRate = 0.123
    },
    [167738] = { -- Gilded Seaweave
        name = "Gilded Seaweave",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1191,
        saleRate = 0.396
    },
    [168185] = { -- Osmenite Ore
        name = "Osmenite Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 3.6607,
        saleRate = 0.272
    },
    [168303] = { -- Rubbery Flank
        name = "Rubbery Flank",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0328,
        saleRate = 0.574
    },
    [168586] = { -- Rising Glory
        name = "Rising Glory",
        subGroup = "1.Very High 10000+",
        marketValue = 9.1638,
        saleRate = 0.653
    },
    [168645] = { -- Moist Fillet
        name = "Moist Fillet",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0312,
        saleRate = 0.473
    },
    [168650] = { -- Cragscale
        name = "Cragscale",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1574,
        saleRate = 0.256
    },
    [169701] = { -- Death Blossom
        name = "Death Blossom",
        subGroup = "1.Very High 10000+",
        marketValue = 9.8397,
        saleRate = 0.813
    },
    [170554] = { -- Vigil's Torch
        name = "Vigil's Torch",
        subGroup = "1.Very High 10000+",
        marketValue = 9.5424,
        saleRate = 0.469
    },
    [171315] = { -- Nightshade
        name = "Nightshade",
        subGroup = "1.Very High 10000+",
        marketValue = 15.8257,
        saleRate = 0.718
    },
    [171828] = { -- Laestrite Ore
        name = "Laestrite Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 6.1479,
        saleRate = 0.772
    },
    [171829] = { -- Solenium Ore
        name = "Solenium Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 1.732,
        saleRate = 0.167
    },
    [171830] = { -- Oxxein Ore
        name = "Oxxein Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 2.2897,
        saleRate = 0.309
    },
    [171831] = { -- Phaedrum Ore
        name = "Phaedrum Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 1.6744,
        saleRate = 0.236
    },
    [171832] = { -- Sinvyr Ore
        name = "Sinvyr Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 1.8128,
        saleRate = 0.174
    },
    [171833] = { -- Elethium Ore
        name = "Elethium Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 5.5505,
        saleRate = 0.62
    },
    [171840] = { -- Porous Stone
        name = "Porous Stone",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0645,
        saleRate = 0.285
    },
    [172052] = { -- Aethereal Meat
        name = "Aethereal Meat",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0693,
        saleRate = 0.246
    },
    [172055] = { -- Phantasmal Haunch
        name = "Phantasmal Haunch",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0705,
        saleRate = 0.111
    },
    [172089] = { -- Desolate Leather
        name = "Desolate Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1084,
        saleRate = 0.115
    },
    [172092] = { -- Pallid Bone
        name = "Pallid Bone",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0557,
        saleRate = 0.222
    },
    [172094] = { -- Callous Hide
        name = "Callous Hide",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1395,
        saleRate = 0.091
    },
    [172096] = { -- Heavy Desolate Leather
        name = "Heavy Desolate Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 1.4308,
        saleRate = 0.248
    },
    [172097] = { -- Heavy Callous Hide
        name = "Heavy Callous Hide",
        subGroup = "1.Very High 10000+",
        marketValue = 1.0953,
        saleRate = 0.294
    },
    [172230] = { -- Soul Dust
        name = "Soul Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0835,
        saleRate = 0.265
    },
    [172231] = { -- Sacred Shard
        name = "Sacred Shard",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2469,
        saleRate = 0.404
    },
    [172232] = { -- Eternal Crystal
        name = "Eternal Crystal",
        subGroup = "1.Very High 10000+",
        marketValue = 1.5625,
        saleRate = 0.111
    },
    [172934] = { -- Handful of Laestrite Bolts
        name = "Handful of Laestrite Bolts",
        subGroup = "1.Very High 10000+",
        marketValue = 7.5747,
        saleRate = 0.213
    },
    [172935] = { -- Porous Polishing Abrasive
        name = "Porous Polishing Abrasive",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0959,
        saleRate = 0.145
    },
    [172937] = { -- Wormfed Gear Assembly
        name = "Wormfed Gear Assembly",
        subGroup = "1.Very High 10000+",
        marketValue = 50.5911,
        saleRate = 0.205
    },
    [173032] = { -- Lost Sole
        name = "Lost Sole",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1185,
        saleRate = 0.721
    },
    [173057] = { -- Luminous Pigment
        name = "Luminous Pigment",
        subGroup = "1.Very High 10000+",
        marketValue = 3.3884,
        saleRate = 0.286
    },
    [173202] = { -- Shrouded Cloth
        name = "Shrouded Cloth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0349,
        saleRate = 0.095
    },
    [173204] = { -- Lightless Silk
        name = "Lightless Silk",
        subGroup = "1.Very High 10000+",
        marketValue = 0.5771,
        saleRate = 0.068
    },
    [174353] = { -- Questionable Meat
        name = "Questionable Meat",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0407,
        saleRate = 0.534
    },
    [179315] = { -- Shadowy Shank
        name = "Shadowy Shank",
        subGroup = "1.Very High 10000+",
        marketValue = 0.07,
        saleRate = 0.344
    },
    [180732] = { -- Rune Etched Vial
        name = "Rune Etched Vial",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0386,
        saleRate = 0.183
    },
    [187699] = { -- First Flower
        name = "First Flower",
        subGroup = "1.Very High 10000+",
        marketValue = 17.283,
        saleRate = 0.11
    },
    [187702] = { -- Precursor Placoderm
        name = "Precursor Placoderm",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1549,
        saleRate = 0.301
    },
    [187703] = { -- Silken Protofiber
        name = "Silken Protofiber",
        subGroup = "1.Very High 10000+",
        marketValue = 0.467,
        saleRate = 0.017
    },
    [187704] = { -- Protoflesh
        name = "Protoflesh",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0799,
        saleRate = 0.156
    },
    [188658] = { -- Draconium Ore
        name = "Draconium Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 22.115,
        saleRate = 0.654
    },
    [189143] = { -- Draconium Ore
        name = "Draconium Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 20.2711,
        saleRate = 0.731
    },
    [190311] = { -- Draconium Ore
        name = "Draconium Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 23.9166,
        saleRate = 0.388
    },
    [190312] = { -- Khaz'gorite Ore
        name = "Khaz'gorite Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 7.6851,
        saleRate = 0.166
    },
    [190313] = { -- Khaz'gorite Ore
        name = "Khaz'gorite Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 7.3296,
        saleRate = 0.172
    },
    [190315] = { -- Rousing Earth
        name = "Rousing Earth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3649,
        saleRate = 0.722
    },
    [190316] = { -- Awakened Earth
        name = "Awakened Earth",
        subGroup = "1.Very High 10000+",
        marketValue = 2.5501,
        saleRate = 0.3
    },
    [190320] = { -- Rousing Fire
        name = "Rousing Fire",
        subGroup = "1.Very High 10000+",
        marketValue = 7.1706,
        saleRate = 0.28
    },
    [190322] = { -- Rousing Order
        name = "Rousing Order",
        subGroup = "1.Very High 10000+",
        marketValue = 4.2486,
        saleRate = 0.573
    },
    [190326] = { -- Rousing Air
        name = "Rousing Air",
        subGroup = "1.Very High 10000+",
        marketValue = 7.0606,
        saleRate = 0.475
    },
    [190327] = { -- Awakened Air
        name = "Awakened Air",
        subGroup = "1.Very High 10000+",
        marketValue = 69.2526,
        saleRate = 0.501
    },
    [190328] = { -- Rousing Frost
        name = "Rousing Frost",
        subGroup = "1.Very High 10000+",
        marketValue = 4.1205,
        saleRate = 0.847
    },
    [190330] = { -- Rousing Decay
        name = "Rousing Decay",
        subGroup = "1.Very High 10000+",
        marketValue = 3.7704,
        saleRate = 0.738
    },
    [190394] = { -- Serevite Ore
        name = "Serevite Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 8.3881,
        saleRate = 0.299
    },
    [190395] = { -- Serevite Ore
        name = "Serevite Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 7.9353,
        saleRate = 0.792
    },
    [190396] = { -- Serevite Ore
        name = "Serevite Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 7.6623,
        saleRate = 0.728
    },
    [190451] = { -- Rousing Ire
        name = "Rousing Ire",
        subGroup = "1.Very High 10000+",
        marketValue = 28.5519,
        saleRate = 0.751
    },
    [190452] = { -- Primal Flux
        name = "Primal Flux",
        subGroup = "1.Very High 10000+",
        marketValue = 3.9207,
        saleRate = 0.651
    },
    [191380] = { -- Refreshing Healing Potion
        name = "Refreshing Healing Potion",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1963,
        saleRate = 0.249
    },
    [191460] = { -- Hochenblume
        name = "Hochenblume",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2296,
        saleRate = 0.376
    },
    [191461] = { -- Hochenblume
        name = "Hochenblume",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1769,
        saleRate = 0.112
    },
    [191462] = { -- Hochenblume
        name = "Hochenblume",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3531,
        saleRate = 0.097
    },
    [191464] = { -- Saxifrage
        name = "Saxifrage",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3472,
        saleRate = 0.422
    },
    [191465] = { -- Saxifrage
        name = "Saxifrage",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3968,
        saleRate = 0.485
    },
    [191466] = { -- Saxifrage
        name = "Saxifrage",
        subGroup = "1.Very High 10000+",
        marketValue = 0.9441,
        saleRate = 0.034
    },
    [191467] = { -- Bubble Poppy
        name = "Bubble Poppy",
        subGroup = "1.Very High 10000+",
        marketValue = 0.8477,
        saleRate = 0.468
    },
    [191468] = { -- Bubble Poppy
        name = "Bubble Poppy",
        subGroup = "1.Very High 10000+",
        marketValue = 1.023,
        saleRate = 0.476
    },
    [191469] = { -- Bubble Poppy
        name = "Bubble Poppy",
        subGroup = "1.Very High 10000+",
        marketValue = 1.379,
        saleRate = 0.182
    },
    [191471] = { -- Writhebark
        name = "Writhebark",
        subGroup = "1.Very High 10000+",
        marketValue = 9.7557,
        saleRate = 0.609
    },
    [191472] = { -- Writhebark
        name = "Writhebark",
        subGroup = "1.Very High 10000+",
        marketValue = 13.96,
        saleRate = 0.266
    },
    [191474] = { -- Draconic Vial
        name = "Draconic Vial",
        subGroup = "1.Very High 10000+",
        marketValue = 4.3082,
        saleRate = 0.155
    },
    [191476] = { -- Draconic Vial
        name = "Draconic Vial",
        subGroup = "1.Very High 10000+",
        marketValue = 5.8597,
        saleRate = 0.372
    },
    [192095] = { -- Spool of Wilderthread
        name = "Spool of Wilderthread",
        subGroup = "1.Very High 10000+",
        marketValue = 1.4663,
        saleRate = 0.384
    },
    [192096] = { -- Spool of Wilderthread
        name = "Spool of Wilderthread",
        subGroup = "1.Very High 10000+",
        marketValue = 1.4499,
        saleRate = 0.466
    },
    [192097] = { -- Spool of Wilderthread
        name = "Spool of Wilderthread",
        subGroup = "1.Very High 10000+",
        marketValue = 1.5267,
        saleRate = 0.312
    },
    [192615] = { -- Fluorescent Fluid
        name = "Fluorescent Fluid",
        subGroup = "1.Very High 10000+",
        marketValue = 0.6211,
        saleRate = 0.243
    },
    [192850] = { -- Eternity Amber
        name = "Eternity Amber",
        subGroup = "1.Very High 10000+",
        marketValue = 3.3554,
        saleRate = 0.349
    },
    [192872] = { -- Fractured Glass
        name = "Fractured Glass",
        subGroup = "1.Very High 10000+",
        marketValue = 0.4402,
        saleRate = 0.44
    },
    [192880] = { -- Crumbled Stone
        name = "Crumbled Stone",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3531,
        saleRate = 0.217
    },
    [193050] = { -- Tattered Wildercloth
        name = "Tattered Wildercloth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.243,
        saleRate = 0.487
    },
    [193053] = { -- Contoured Fowlfeather
        name = "Contoured Fowlfeather",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1098,
        saleRate = 0.606
    },
    [193208] = { -- Resilient Leather
        name = "Resilient Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2025,
        saleRate = 0.609
    },
    [193210] = { -- Resilient Leather
        name = "Resilient Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1533,
        saleRate = 0.725
    },
    [193211] = { -- Resilient Leather
        name = "Resilient Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2875,
        saleRate = 0.123
    },
    [193214] = { -- Adamant Scales
        name = "Adamant Scales",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1313,
        saleRate = 0.518
    },
    [193215] = { -- Adamant Scales
        name = "Adamant Scales",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1947,
        saleRate = 0.516
    },
    [193217] = { -- Dense Hide
        name = "Dense Hide",
        subGroup = "1.Very High 10000+",
        marketValue = 1.4595,
        saleRate = 0.456
    },
    [193223] = { -- Lustrous Scaled Hide
        name = "Lustrous Scaled Hide",
        subGroup = "1.Very High 10000+",
        marketValue = 1.7591,
        saleRate = 0.448
    },
    [193253] = { -- Cacophonous Thunderscale
        name = "Cacophonous Thunderscale",
        subGroup = "1.Very High 10000+",
        marketValue = 2.3838,
        saleRate = 0.601
    },
    [193254] = { -- Rockfang Leather
        name = "Rockfang Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 19.7682,
        saleRate = 0.505
    },
    [193255] = { -- Pristine Vorquin Horn
        name = "Pristine Vorquin Horn",
        subGroup = "1.Very High 10000+",
        marketValue = 0.7716,
        saleRate = 0.417
    },
    [193258] = { -- Fire-Infused Hide
        name = "Fire-Infused Hide",
        subGroup = "1.Very High 10000+",
        marketValue = 0.9226,
        saleRate = 0.086
    },
    [193259] = { -- Flawless Proto Dragon Scale
        name = "Flawless Proto Dragon Scale",
        subGroup = "1.Very High 10000+",
        marketValue = 0.133,
        saleRate = 0.451
    },
    [193261] = { -- Bite-Sized Morsel
        name = "Bite-Sized Morsel",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0565,
        saleRate = 0.527
    },
    [193368] = { -- Silken Gemdust
        name = "Silken Gemdust",
        subGroup = "1.Very High 10000+",
        marketValue = 1.9455,
        saleRate = 0.264
    },
    [193369] = { -- Silken Gemdust
        name = "Silken Gemdust",
        subGroup = "1.Very High 10000+",
        marketValue = 1.1389,
        saleRate = 0.12
    },
    [193370] = { -- Silken Gemdust
        name = "Silken Gemdust",
        subGroup = "1.Very High 10000+",
        marketValue = 1.6443,
        saleRate = 0.249
    },
    [193922] = { -- Wildercloth
        name = "Wildercloth",
        subGroup = "1.Very High 10000+",
        marketValue = 5.062,
        saleRate = 0.778
    },
    [193924] = { -- Frostbitten Wildercloth
        name = "Frostbitten Wildercloth",
        subGroup = "1.Very High 10000+",
        marketValue = 4.9697,
        saleRate = 0.582
    },
    [193927] = { -- Wildercloth Bolt
        name = "Wildercloth Bolt",
        subGroup = "1.Very High 10000+",
        marketValue = 13.6062,
        saleRate = 0.45
    },
    [193928] = { -- Wildercloth Bolt
        name = "Wildercloth Bolt",
        subGroup = "1.Very High 10000+",
        marketValue = 12.8624,
        saleRate = 0.29
    },
    [194123] = { -- Chromatic Dust
        name = "Chromatic Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 2.2205,
        saleRate = 0.795
    },
    [194730] = { -- Scalebelly Mackerel
        name = "Scalebelly Mackerel",
        subGroup = "1.Very High 10000+",
        marketValue = 0.441,
        saleRate = 0.762
    },
    [194852] = { -- Flourishing Ink
        name = "Flourishing Ink",
        subGroup = "1.Very High 10000+",
        marketValue = 11.678,
        saleRate = 0.232
    },
    [194858] = { -- Serene Ink
        name = "Serene Ink",
        subGroup = "1.Very High 10000+",
        marketValue = 3.9954,
        saleRate = 0.206
    },
    [194966] = { -- Thousandbite Piranha
        name = "Thousandbite Piranha",
        subGroup = "1.Very High 10000+",
        marketValue = 0.4454,
        saleRate = 0.705
    },
    [194967] = { -- Aileron Seamoth
        name = "Aileron Seamoth",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3885,
        saleRate = 0.527
    },
    [194968] = { -- Cerulean Spinefish
        name = "Cerulean Spinefish",
        subGroup = "1.Very High 10000+",
        marketValue = 0.5077,
        saleRate = 0.588
    },
    [194970] = { -- Islefin Dorado
        name = "Islefin Dorado",
        subGroup = "1.Very High 10000+",
        marketValue = 0.6053,
        saleRate = 0.17
    },
    [197741] = { -- Maybe Meat
        name = "Maybe Meat",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0287,
        saleRate = 0.604
    },
    [197742] = { -- Ribbed Mollusk Meat
        name = "Ribbed Mollusk Meat",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0904,
        saleRate = 0.409
    },
    [197745] = { -- Basilisk Eggs
        name = "Basilisk Eggs",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1454,
        saleRate = 0.538
    },
    [197746] = { -- Bruffalon Flank
        name = "Bruffalon Flank",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0426,
        saleRate = 0.36
    },
    [197751] = { -- Pastry Packets
        name = "Pastry Packets",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1507,
        saleRate = 0.345
    },
    [197754] = { -- Salt Deposit
        name = "Salt Deposit",
        subGroup = "1.Very High 10000+",
        marketValue = 0.037,
        saleRate = 0.528
    },
    [197755] = { -- Lava Beetle
        name = "Lava Beetle",
        subGroup = "1.Very High 10000+",
        marketValue = 0.06,
        saleRate = 0.445
    },
    [197756] = { -- Pebbled Rock Salts
        name = "Pebbled Rock Salts",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0716,
        saleRate = 0.127
    },
    [197757] = { -- Assorted Exotic Spices
        name = "Assorted Exotic Spices",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0401,
        saleRate = 0.14
    },
    [198185] = { -- Handful of Serevite Bolts
        name = "Handful of Serevite Bolts",
        subGroup = "1.Very High 10000+",
        marketValue = 8.9532,
        saleRate = 0.215
    },
    [198188] = { -- Shock-Spring Coil
        name = "Shock-Spring Coil",
        subGroup = "1.Very High 10000+",
        marketValue = 29.1857,
        saleRate = 0.02
    },
    [198194] = { -- Greased-Up Gears
        name = "Greased-Up Gears",
        subGroup = "1.Very High 10000+",
        marketValue = 57.8279,
        saleRate = 0.038
    },
    [198421] = { -- Shimmering Pigment
        name = "Shimmering Pigment",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2615,
        saleRate = 0.228
    },
    [198422] = { -- Shimmering Pigment
        name = "Shimmering Pigment",
        subGroup = "1.Very High 10000+",
        marketValue = 0.484,
        saleRate = 0.127
    },
    [198423] = { -- Shimmering Pigment
        name = "Shimmering Pigment",
        subGroup = "1.Very High 10000+",
        marketValue = 1.1619,
        saleRate = 0.063
    },
    [198487] = { -- Iridescent Water
        name = "Iridescent Water",
        subGroup = "1.Very High 10000+",
        marketValue = 1.0456,
        saleRate = 0.332
    },
    [199344] = { -- Magma Thresher
        name = "Magma Thresher",
        subGroup = "1.Very High 10000+",
        marketValue = 1.0512,
        saleRate = 0.393
    },
    [200113] = { -- Resonant Crystal
        name = "Resonant Crystal",
        subGroup = "1.Very High 10000+",
        marketValue = 56.0257,
        saleRate = 0.563
    },
    [200506] = { -- Roused Seedling
        name = "Roused Seedling",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2271,
        saleRate = 0.471
    },
    [200507] = { -- Decayed Roused Seedling
        name = "Decayed Roused Seedling",
        subGroup = "1.Very High 10000+",
        marketValue = 1.3245,
        saleRate = 0.044
    },
    [204460] = { -- Zaralek Glowspores
        name = "Zaralek Glowspores",
        subGroup = "1.Very High 10000+",
        marketValue = 1.9011,
        saleRate = 0.56
    },
    [210221] = { -- Forged Combatant's Heraldry
        name = "Forged Combatant's Heraldry",
        subGroup = "1.Very High 10000+",
        marketValue = 0.621,
        saleRate = 0.451
    },
    [210796] = { -- Mycobloom
        name = "Mycobloom",
        subGroup = "1.Very High 10000+",
        marketValue = 14.2435,
        saleRate = 0.904
    },
    [210797] = { -- Mycobloom
        name = "Mycobloom",
        subGroup = "1.Very High 10000+",
        marketValue = 14.472,
        saleRate = 0.867
    },
    [210798] = { -- Mycobloom
        name = "Mycobloom",
        subGroup = "1.Very High 10000+",
        marketValue = 16.959,
        saleRate = 0.63
    },
    [210799] = { -- Luredrop
        name = "Luredrop",
        subGroup = "1.Very High 10000+",
        marketValue = 33.4661,
        saleRate = 0.675
    },
    [210800] = { -- Luredrop
        name = "Luredrop",
        subGroup = "1.Very High 10000+",
        marketValue = 33.3175,
        saleRate = 0.393
    },
    [210801] = { -- Luredrop
        name = "Luredrop",
        subGroup = "1.Very High 10000+",
        marketValue = 172.4995,
        saleRate = 0.495
    },
    [210802] = { -- Orbinid
        name = "Orbinid",
        subGroup = "1.Very High 10000+",
        marketValue = 13.1932,
        saleRate = 0.72
    },
    [210803] = { -- Orbinid
        name = "Orbinid",
        subGroup = "1.Very High 10000+",
        marketValue = 13.1554,
        saleRate = 0.307
    },
    [210804] = { -- Orbinid
        name = "Orbinid",
        subGroup = "1.Very High 10000+",
        marketValue = 71.9448,
        saleRate = 0.45
    },
    [210805] = { -- Blessing Blossom
        name = "Blessing Blossom",
        subGroup = "1.Very High 10000+",
        marketValue = 11.3936,
        saleRate = 0.895
    },
    [210806] = { -- Blessing Blossom
        name = "Blessing Blossom",
        subGroup = "1.Very High 10000+",
        marketValue = 11.7575,
        saleRate = 0.6
    },
    [210807] = { -- Blessing Blossom
        name = "Blessing Blossom",
        subGroup = "1.Very High 10000+",
        marketValue = 61.4833,
        saleRate = 0.64
    },
    [210808] = { -- Arathor's Spear
        name = "Arathor's Spear",
        subGroup = "1.Very High 10000+",
        marketValue = 30.566,
        saleRate = 0.717
    },
    [210809] = { -- Arathor's Spear
        name = "Arathor's Spear",
        subGroup = "1.Very High 10000+",
        marketValue = 31.1425,
        saleRate = 0.399
    },
    [210810] = { -- Arathor's Spear
        name = "Arathor's Spear",
        subGroup = "1.Very High 10000+",
        marketValue = 162.4098,
        saleRate = 0.588
    },
    [210930] = { -- Bismuth
        name = "Bismuth",
        subGroup = "1.Very High 10000+",
        marketValue = 19.3568,
        saleRate = 0.906
    },
    [210931] = { -- Bismuth
        name = "Bismuth",
        subGroup = "1.Very High 10000+",
        marketValue = 21.9206,
        saleRate = 0.848
    },
    [210932] = { -- Bismuth
        name = "Bismuth",
        subGroup = "1.Very High 10000+",
        marketValue = 116.584,
        saleRate = 0.8
    },
    [210933] = { -- Aqirite
        name = "Aqirite",
        subGroup = "1.Very High 10000+",
        marketValue = 12.5333,
        saleRate = 0.878
    },
    [210934] = { -- Aqirite
        name = "Aqirite",
        subGroup = "1.Very High 10000+",
        marketValue = 13.7158,
        saleRate = 0.761
    },
    [210935] = { -- Aqirite
        name = "Aqirite",
        subGroup = "1.Very High 10000+",
        marketValue = 18.1539,
        saleRate = 0.691
    },
    [210936] = { -- Ironclaw Ore
        name = "Ironclaw Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 12.3825,
        saleRate = 0.821
    },
    [210937] = { -- Ironclaw Ore
        name = "Ironclaw Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 13.685,
        saleRate = 0.798
    },
    [210938] = { -- Ironclaw Ore
        name = "Ironclaw Ore",
        subGroup = "1.Very High 10000+",
        marketValue = 18.7444,
        saleRate = 0.772
    },
    [211474] = { -- Shadowblind Grouper
        name = "Shadowblind Grouper",
        subGroup = "1.Very High 10000+",
        marketValue = 2.5469,
        saleRate = 0.336
    },
    [211806] = { -- Gilded Vial
        name = "Gilded Vial",
        subGroup = "1.Very High 10000+",
        marketValue = 2.4614,
        saleRate = 0.669
    },
    [211878] = { -- Algari Healing Potion
        name = "Algari Healing Potion",
        subGroup = "1.Very High 10000+",
        marketValue = 15.7252,
        saleRate = 0.477
    },
    [212242] = { -- Cavedweller's Delight
        name = "Cavedweller's Delight",
        subGroup = "1.Very High 10000+",
        marketValue = 7.9509,
        saleRate = 0.826
    },
    [212257] = { -- Potion of Unwavering Focus
        name = "Potion of Unwavering Focus",
        subGroup = "1.Very High 10000+",
        marketValue = 13.2259,
        saleRate = 0.707
    },
    [212495] = { -- Radiant Ruby
        name = "Radiant Ruby",
        subGroup = "1.Very High 10000+",
        marketValue = 96.8436,
        saleRate = 0.41
    },
    [212498] = { -- Ambivalent Amber
        name = "Ambivalent Amber",
        subGroup = "1.Very High 10000+",
        marketValue = 5.8695,
        saleRate = 0.601
    },
    [212505] = { -- Extravagant Emerald
        name = "Extravagant Emerald",
        subGroup = "1.Very High 10000+",
        marketValue = 97.9277,
        saleRate = 0.427
    },
    [212508] = { -- Stunning Sapphire
        name = "Stunning Sapphire",
        subGroup = "1.Very High 10000+",
        marketValue = 96.2444,
        saleRate = 0.462
    },
    [212511] = { -- Ostentatious Onyx
        name = "Ostentatious Onyx",
        subGroup = "1.Very High 10000+",
        marketValue = 97.4471,
        saleRate = 0.424
    },
    [212664] = { -- Stormcharged Leather
        name = "Stormcharged Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 11.2595,
        saleRate = 0.867
    },
    [212665] = { -- Stormcharged Leather
        name = "Stormcharged Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 11.4,
        saleRate = 0.74
    },
    [212666] = { -- Stormcharged Leather
        name = "Stormcharged Leather",
        subGroup = "1.Very High 10000+",
        marketValue = 12.005,
        saleRate = 0.349
    },
    [212667] = { -- Gloom Chitin
        name = "Gloom Chitin",
        subGroup = "1.Very High 10000+",
        marketValue = 11.5213,
        saleRate = 0.869
    },
    [212668] = { -- Gloom Chitin
        name = "Gloom Chitin",
        subGroup = "1.Very High 10000+",
        marketValue = 11.6107,
        saleRate = 0.788
    },
    [212669] = { -- Gloom Chitin
        name = "Gloom Chitin",
        subGroup = "1.Very High 10000+",
        marketValue = 11.7088,
        saleRate = 0.58
    },
    [213220] = { -- Crushed Gemstones
        name = "Crushed Gemstones",
        subGroup = "1.Very High 10000+",
        marketValue = 52.2294,
        saleRate = 0.234
    },
    [213398] = { -- Handful of Pebbles
        name = "Handful of Pebbles",
        subGroup = "1.Very High 10000+",
        marketValue = 1.344,
        saleRate = 0.501
    },
    [213399] = { -- Glittering Glass
        name = "Glittering Glass",
        subGroup = "1.Very High 10000+",
        marketValue = 17.8084,
        saleRate = 0.643
    },
    [213610] = { -- Crystalline Powder
        name = "Crystalline Powder",
        subGroup = "1.Very High 10000+",
        marketValue = 1.1341,
        saleRate = 0.595
    },
    [213611] = { -- Writhing Sample
        name = "Writhing Sample",
        subGroup = "1.Very High 10000+",
        marketValue = 30.0082,
        saleRate = 0.721
    },
    [213612] = { -- Viridescent Spores
        name = "Viridescent Spores",
        subGroup = "1.Very High 10000+",
        marketValue = 37.0021,
        saleRate = 0.815
    },
    [213613] = { -- Leyline Residue
        name = "Leyline Residue",
        subGroup = "1.Very High 10000+",
        marketValue = 138.6618,
        saleRate = 0.84
    },
    [218336] = { -- Kaheti Swarm Chitin
        name = "Kaheti Swarm Chitin",
        subGroup = "1.Very High 10000+",
        marketValue = 0.8676,
        saleRate = 0.347
    },
    [218337] = { -- Honed Bone Shards
        name = "Honed Bone Shards",
        subGroup = "1.Very High 10000+",
        marketValue = 38.9858,
        saleRate = 0.584
    },
    [218338] = { -- Bottled Storm
        name = "Bottled Storm",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1564,
        saleRate = 0.487
    },
    [218339] = { -- Burning Cinderbee Setae
        name = "Burning Cinderbee Setae",
        subGroup = "1.Very High 10000+",
        marketValue = 0.129,
        saleRate = 0.51
    },
    [219946] = { -- Storm Dust
        name = "Storm Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 21.5265,
        saleRate = 0.589
    },
    [219947] = { -- Storm Dust
        name = "Storm Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 27.8091,
        saleRate = 0.545
    },
    [219948] = { -- Storm Dust
        name = "Storm Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 126.7279,
        saleRate = 0.361
    },
    [219949] = { -- Gleaming Shard
        name = "Gleaming Shard",
        subGroup = "1.Very High 10000+",
        marketValue = 68.7734,
        saleRate = 0.63
    },
    [219950] = { -- Gleaming Shard
        name = "Gleaming Shard",
        subGroup = "1.Very High 10000+",
        marketValue = 74.5788,
        saleRate = 0.584
    },
    [220134] = { -- Dilly-Dally Dace
        name = "Dilly-Dally Dace",
        subGroup = "1.Very High 10000+",
        marketValue = 16.6348,
        saleRate = 0.866
    },
    [220135] = { -- Bloody Perch
        name = "Bloody Perch",
        subGroup = "1.Very High 10000+",
        marketValue = 16.2323,
        saleRate = 0.937
    },
    [220136] = { -- Crystalline Sturgeon
        name = "Crystalline Sturgeon",
        subGroup = "1.Very High 10000+",
        marketValue = 16.4478,
        saleRate = 0.939
    },
    [220137] = { -- Bismuth Bitterling
        name = "Bismuth Bitterling",
        subGroup = "1.Very High 10000+",
        marketValue = 16.417,
        saleRate = 0.917
    },
    [220138] = { -- Nibbling Minnow
        name = "Nibbling Minnow",
        subGroup = "1.Very High 10000+",
        marketValue = 16.6836,
        saleRate = 0.763
    },
    [220139] = { -- Whispering Stargazer
        name = "Whispering Stargazer",
        subGroup = "1.Very High 10000+",
        marketValue = 20.8046,
        saleRate = 0.77
    },
    [221763] = { -- Viridian Charmcap
        name = "Viridian Charmcap",
        subGroup = "1.Very High 10000+",
        marketValue = 681.1673,
        saleRate = 0.464
    },
    [221853] = { -- Handful of Bismuth Bolts
        name = "Handful of Bismuth Bolts",
        subGroup = "1.Very High 10000+",
        marketValue = 41.3477,
        saleRate = 0.566
    },
    [222555] = { -- Codified Greenwood
        name = "Codified Greenwood",
        subGroup = "1.Very High 10000+",
        marketValue = 57.4817,
        saleRate = 0.719
    },
    [222609] = { -- Shadow Ink
        name = "Shadow Ink",
        subGroup = "1.Very High 10000+",
        marketValue = 59.6663,
        saleRate = 0.626
    },
    [222618] = { -- Nacreous Pigment
        name = "Nacreous Pigment",
        subGroup = "1.Very High 10000+",
        marketValue = 10.709,
        saleRate = 0.446
    },
    [222695] = { -- Twined Herbs
        name = "Twined Herbs",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1902,
        saleRate = 0.32
    },
    [222696] = { -- Crunchy Peppers
        name = "Crunchy Peppers",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1185,
        saleRate = 0.239
    },
    [222697] = { -- Coreway Dust
        name = "Coreway Dust",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1452,
        saleRate = 0.585
    },
    [222699] = { -- Khaz Algar Tomato
        name = "Khaz Algar Tomato",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1646,
        saleRate = 0.346
    },
    [222700] = { -- Granulated Spices
        name = "Granulated Spices",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1093,
        saleRate = 0.267
    },
    [222701] = { -- Clumped Flour
        name = "Clumped Flour",
        subGroup = "1.Very High 10000+",
        marketValue = 0.0939,
        saleRate = 0.262
    },
    [222728] = { -- Beledar's Bounty
        name = "Beledar's Bounty",
        subGroup = "1.Very High 10000+",
        marketValue = 33.265,
        saleRate = 0.618
    },
    [222737] = { -- Chopped Mycobloom
        name = "Chopped Mycobloom",
        subGroup = "1.Very High 10000+",
        marketValue = 12.2931,
        saleRate = 0.373
    },
    [222738] = { -- Portioned Steak
        name = "Portioned Steak",
        subGroup = "1.Very High 10000+",
        marketValue = 6.2384,
        saleRate = 0.64
    },
    [222739] = { -- Spiced Meat Stock
        name = "Spiced Meat Stock",
        subGroup = "1.Very High 10000+",
        marketValue = 6.6413,
        saleRate = 0.527
    },
    [222741] = { -- Fresh Fillet
        name = "Fresh Fillet",
        subGroup = "1.Very High 10000+",
        marketValue = 20.3201,
        saleRate = 0.574
    },
    [222789] = { -- Spool of Duskthread
        name = "Spool of Duskthread",
        subGroup = "1.Very High 10000+",
        marketValue = 42.3587,
        saleRate = 0.234
    },
    [222790] = { -- Spool of Duskthread
        name = "Spool of Duskthread",
        subGroup = "1.Very High 10000+",
        marketValue = 38.6954,
        saleRate = 0.239
    },
    [222792] = { -- Spool of Dawnthread
        name = "Spool of Dawnthread",
        subGroup = "1.Very High 10000+",
        marketValue = 14.2803,
        saleRate = 0.172
    },
    [222793] = { -- Spool of Dawnthread
        name = "Spool of Dawnthread",
        subGroup = "1.Very High 10000+",
        marketValue = 13.7223,
        saleRate = 0.208
    },
    [222795] = { -- Spool of Weaverthread
        name = "Spool of Weaverthread",
        subGroup = "1.Very High 10000+",
        marketValue = 8.6731,
        saleRate = 0.736
    },
    [222804] = { -- Weavercloth Bolt
        name = "Weavercloth Bolt",
        subGroup = "1.Very High 10000+",
        marketValue = 56.1403,
        saleRate = 0.615
    },
    [222805] = { -- Weavercloth Bolt
        name = "Weavercloth Bolt",
        subGroup = "1.Very High 10000+",
        marketValue = 56.5008,
        saleRate = 0.555
    },
    [222806] = { -- Weavercloth Bolt
        name = "Weavercloth Bolt",
        subGroup = "1.Very High 10000+",
        marketValue = 57.225,
        saleRate = 0.502
    },
    [223512] = { -- Basically Beef
        name = "Basically Beef",
        subGroup = "1.Very High 10000+",
        marketValue = 6.8954,
        saleRate = 0.806
    },
    [224762] = { -- Delver's Waterskin
        name = "Delver's Waterskin",
        subGroup = "1.Very High 10000+",
        marketValue = 1.2678,
        saleRate = 0.604
    },
    [224764] = { -- Mosswool Thread
        name = "Mosswool Thread",
        subGroup = "1.Very High 10000+",
        marketValue = 0.1283,
        saleRate = 0.59
    },
    [224805] = { -- Blossom Pigment
        name = "Blossom Pigment",
        subGroup = "1.Very High 10000+",
        marketValue = 8.8494,
        saleRate = 0.369
    },
    [224824] = { -- Duskweave
        name = "Duskweave",
        subGroup = "1.Very High 10000+",
        marketValue = 32.3442,
        saleRate = 0.66
    },
    [224826] = { -- Dawnweave
        name = "Dawnweave",
        subGroup = "1.Very High 10000+",
        marketValue = 10.6367,
        saleRate = 0.565
    },
    [224828] = { -- Weavercloth
        name = "Weavercloth",
        subGroup = "1.Very High 10000+",
        marketValue = 27.0761,
        saleRate = 0.867
    },
    [225565] = { -- Massive Worm Flank
        name = "Massive Worm Flank",
        subGroup = "1.Very High 10000+",
        marketValue = 6.785,
        saleRate = 0.643
    },
    [225566] = { -- Warped Wing
        name = "Warped Wing",
        subGroup = "1.Very High 10000+",
        marketValue = 6.4986,
        saleRate = 0.702
    },
    [225567] = { -- Bug Brisket
        name = "Bug Brisket",
        subGroup = "1.Very High 10000+",
        marketValue = 6.7781,
        saleRate = 0.883
    },
    [225569] = { -- Clipped Bird Wing
        name = "Clipped Bird Wing",
        subGroup = "1.Very High 10000+",
        marketValue = 5.9732,
        saleRate = 0.678
    },
    [225911] = { -- Cinderbee Belly
        name = "Cinderbee Belly",
        subGroup = "1.Very High 10000+",
        marketValue = 7.4786,
        saleRate = 0.765
    },
    [225912] = { -- Hot Honeycomb
        name = "Hot Honeycomb",
        subGroup = "1.Very High 10000+",
        marketValue = 40.8306,
        saleRate = 0.479
    },
    [226037] = { -- Timeless Neural Silencer
        name = "Timeless Neural Silencer",
        subGroup = "1.Very High 10000+",
        marketValue = 26.849,
        saleRate = 0.093
    },
    [226202] = { -- Echoing Flux
        name = "Echoing Flux",
        subGroup = "1.Very High 10000+",
        marketValue = 0.3471,
        saleRate = 0.466
    },
    [226204] = { -- Fresh Parchment
        name = "Fresh Parchment",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2929,
        saleRate = 0.181
    },
    [226205] = { -- Distilled Algari Freshwater
        name = "Distilled Algari Freshwater",
        subGroup = "1.Very High 10000+",
        marketValue = 0.033,
        saleRate = 0.248
    },
    [227769] = { -- Bountiful Bolts
        name = "Bountiful Bolts",
        subGroup = "1.Very High 10000+",
        marketValue = 4.2895,
        saleRate = 0.442
    },
    [228231] = { -- Weavercloth
        name = "Weavercloth",
        subGroup = "1.Very High 10000+",
        marketValue = 27.2502,
        saleRate = 0.641
    },
    [228232] = { -- Weavercloth
        name = "Weavercloth",
        subGroup = "1.Very High 10000+",
        marketValue = 27.83,
        saleRate = 0.678
    },
    [228233] = { -- Duskweave
        name = "Duskweave",
        subGroup = "1.Very High 10000+",
        marketValue = 32.5076,
        saleRate = 0.535
    },
    [228234] = { -- Duskweave
        name = "Duskweave",
        subGroup = "1.Very High 10000+",
        marketValue = 36.8049,
        saleRate = 0.463
    },
    [228235] = { -- Dawnweave
        name = "Dawnweave",
        subGroup = "1.Very High 10000+",
        marketValue = 10.8015,
        saleRate = 0.504
    },
    [228236] = { -- Dawnweave
        name = "Dawnweave",
        subGroup = "1.Very High 10000+",
        marketValue = 16.5511,
        saleRate = 0.322
    },
    [228414] = { -- Frayed Wiring
        name = "Frayed Wiring",
        subGroup = "1.Very High 10000+",
        marketValue = 3.8411,
        saleRate = 0.385
    },
    [228930] = { -- Adorning Ribbon
        name = "Adorning Ribbon",
        subGroup = "1.Very High 10000+",
        marketValue = 0.2212,
        saleRate = 0.384
    },
}
